### ISSUE TITLE
House images are not uploading correctly

### ISSUE THREAD

**Issue by manytostao** [Codechanic/manager.rent.cu#5]
Hey @firomero, images are being sent into the symfony backend as FormData. To test out sending them as binary, just call the `uploadImage` method on the `imageService` here with a third boolean parameter with the value `true`:
https://github.com/Codechanic/manager.rent.cu/blob/0f90d173edf7e75e429393409bb6b89a58f26c60/src/app/shared/image-upload/image-upload.component.ts#L42

This code is in the `feature/image-upload` branch.

**Comment by yelena870513** [comment]
Thanks @manytostao will review and fit the upload to this.
